sales/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import sales_home, plot_and_show, upload_xlsx, FileUploadView

app_name = 'sales'

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', sales_home),
    # path('upload_xlsx/', upload_xlsx, name='upload_xlsx'),
    path('upload_xlsx/', FileUploadView.as_view(), name='upload_xlsx'),
    path('plot_and_show/', plot_and_show, name='plot_and_show'),
]

urlpatterns += staticfiles_urlpatterns()

salesdata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings # new
from django.conf.urls.static import static # new

from sales.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('sales.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', index_view),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/models.py
from django.db import models

# Create your models here.
class UploadFile(models.Model):
    file = models.FileField(upload_to="files/")

sales/forms.py
from django import forms
from .models import UploadFile

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['file']

sales/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .functions import create_plot_from_xlsx
from .models import UploadFile
from .forms import UploadFileForm


# Create your views here.
def index_view(request):
    # return render(request, )
    return HttpResponse("<h1>this is project homepage</h1>")

def sales_home(request):
    return HttpResponse("<h1>this is sales app homepage</h1>")

def upload_xlsx(request):
    return render(request, 'sales/plot_data.html')

class FileUploadView(CreateView):
    model = UploadFile
    form_class = UploadFileForm
    template_name = 'sales/plot_data.html'
    success_url = reverse_lazy('sales:plot_and_show')

def plot_and_show(request):
    # processing csv file and createing images
    # filename = request.FILES['sales_data_file'].name
    # print(filename)
    # fetching latest file name with path
    file = UploadFile.objects.order_by('-id')[0]
    file_path = settings.BASE_DIR + file.file.url
    # print(settings.BASE_DIR)
    # print(file_path)
    # print(filename)
    create_plot_from_xlsx(file_path, "Sheet1")

    # showing images
    return render(request, 'sales/plot_and_show.html')

sales/templates/sales/plot_and_show.html
{% load static%}

# showing created figures
<h2>age box plot</h2>
<img src="{% static 'sales/age_box_plot.png' %}" width=500 height=500>

<h2>age histogram</h2>
<img src="{% static 'sales/age_histogram.png' %}" width=500 height=500>

<h2>bmi barplot</h2>
<img src="{% static 'sales/bmi_bar_plot.png' %}" width=500 height=500>

<h2>gender barplot</h2>
<img src="{% static 'sales/gender_bar_plot.png' %}" width=500 height=500>

<h2>income distribution</h2>
<img src="{% static 'sales/income_distribution.png' %}" width=500 height=500>

sales/templates/sales/plot_data.html
select the 

<form method='post' enctype="multipart/form-data">
{% csrf_token %}
{% comment %} <input type='file' name='sales_data_file'> {% endcomment %}
{{form.as_p}}
<input type='submit'>

</form>

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}! <br><br>

  click <a href="{% url 'sales:upload_xlsx' %}">hear</a> for uploading xlsx file and show figures
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}